---
title: "Metodos numericos"
output: html_notebook
---



```{r}
f <- function (x) {
  return (exp(x) - pi*x)
}

plot(f)

vec <- 0

```

## Metodo de Newton-Raphson

```{r}

fprima <- function(x){
  return (exp(x) - pi)
} 

newtonR <- function(x){

  E <- 1
  error <- 1e-5
  x1<-0 
  iteraciones<-0
  vec <-0
  
  while(error < E){
    
    iteraciones <- iteraciones+1  
    x1 <- x - f(x)/fprima(x)
    E <- abs(x1-x)/abs(x1)
    x <- x1
    
    vec<-c(vec,E)
    
  }
  E <<- E
  iteraciones <<- iteraciones
  vec <<- vec
  
  return(x)
  
}


cat("Primera raiz: ", newtonR(1), "\nError: ", E , "\nIteraciones:", iteraciones)
plot(vec[2:iteraciones], xlab="Iteracion", ylab="Error")

cat("Segunda raiz: ", newtonR(2), "\nError: ", E, "\nIteraciones:", iteraciones)
plot(vec[2:iteraciones], xlab="Iteracion", ylab="Error")
```

## Metodo de biseccion

```{r}

biseccion <- function(a,b){
  
  
  E <- b-a
  error<- 1e-5
  x<-0
  iteraciones<-0
  vec <-0
  
  while (error < E){
      
    x<- (a+b)/2
    
    if(f(x)*f(a) < 0 )
      b = x
    if(f(x)*f(b) < 0)
      a = x
    
    E <- (b-a)/2
    
    vec<-c(vec,E)
    
    iteraciones<-iteraciones+1
  }
  
  vec<<-vec
  iteraciones <<- iteraciones
  E <<- E
  
  return(x)
}

E<-0

cat("La primera raiz es: ", biseccion(0,1), "\nError: ", E, "\nIteraciones:", iteraciones)
plot(vec[2:iteraciones], xlab="Iteracion", ylab="Error")

cat("La segunda raiz es: ", biseccion(1,2), "\nError: ", E, "\nIteraciones:", iteraciones)
plot(vec[2:iteraciones], xlab="Iteracion", ylab="Error")

```

## Metodo de Punto fijo

```{r}

g <- function (x) {
  return (exp(x)/pi)
}

puntofijo <- function(a,b){
  
  error<-1e-5
  x<- a
  E<-b-a
  iteraciones<-0
  
  
  if((g(a)-a)*(g(b)-b) > 0)
  {
    return("No existe la raiz en el intervalo especificado")
    
  }
  
  while(error < E)
  {
    x1 <- g(x)
    
    E <- abs(x1 -x)
    
    x <- x1 
      
    vec<-c(vec,E)
    
    iteraciones <- iteraciones+1
  }
  
  vec<<-vec
  iteraciones<<-iteraciones
  
  return(cat("Raiz: " , x1 , "\nError: ", E, "\nIteraciones:", iteraciones))

}

vec<-0
iteraciones<-0
```
### Resultado
```{r}
puntofijo(0,1)

plot(vec[2:iteraciones], xlab="Iteracion", ylab="Error")
```


##Conclusion

Tal y como se puede observar en los datos anteriores, el Metodo de Newton-Raphson es el que mejor converge, ademas presenta el error mas pequeno entre los 3 metodos. No obstante, este metodo tiene el problema de que no se puede garantizar que siempre encuentre la solucion.

